version: '3'

services:
  nginx:
    volumes:
      - hahahaha-sync:/var/www:nocopy
  php-fpm:
    volumes:
      - hahahaha-sync:/var/www:nocopy
  workspace:
    volumes:
      - hahahaha-sync:/var/www:nocopy

volumes:
  hahahaha-sync:
    external: true
