version: '3'

services:
  nginx:
    volumes:
      - hrs-sync:/var/www:nocopy
  php-fpm:
    volumes:
      - hrs-sync:/var/www:nocopy
  workspace:
    volumes:
      - hrs-sync:/var/www:nocopy

volumes:
  hrs-sync:
    external: true
